18:35:28.573 [Abstract Blocking TAE Async Processing Thread (1-1)] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - This version of SMAC hardcodes run length for calls to the target algorithm to 2147483647.
18:35:28.801 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x000B, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:35:28:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:35:53.204 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x000B, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:35:53:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:35:53.205 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x000B, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.20/24.29	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:35:53.205 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x000B, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.20/24.29	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:35:53.205 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x000B, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.20/24.29	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:35:53.205 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x000B, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:35:53.206 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x000B, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:35:53:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 24.356400, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-35-28-753136_run_instance.out.The output status is not "SAT"
18:35:53.631 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3779, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:35:53:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:35:54.934 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3779, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:35:54:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:35:54.935 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3779, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.20	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:35:54.935 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3779, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.20	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:35:54.935 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3779, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.20	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:35:54.935 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3779, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:35:54.986 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3779, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:35:54:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.254170, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-35-53-599478_run_instance.out.The output status is not "SAT"
18:35:55.146 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x754F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:35:55:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:35:56.449 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x754F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:35:56:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:35:56.449 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x754F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.21	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:35:56.450 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x754F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.21	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:35:56.450 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x754F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.21	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:35:56.450 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x754F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:35:56.501 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x754F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:35:56:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.263430, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-35-55-121189_run_instance.out.The output status is not "SAT"
18:35:56.778 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCEB, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:35:56:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:35:58.181 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCEB, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:35:58:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:35:58.182 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCEB, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.28	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:35:58.182 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCEB, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.28	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:35:58.182 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCEB, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.28	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:35:58.182 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCEB, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:35:58.232 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCEB, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:35:58:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.339460, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-35-56-736404_run_instance.out.The output status is not "SAT"
18:35:58.535 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x11EF4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:35:58:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:35:59.939 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x11EF4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:35:59:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:35:59.939 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x11EF4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.25	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:35:59.939 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x11EF4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.25	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:35:59.939 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x11EF4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.25	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:35:59.939 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x11EF4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:35:59.990 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x11EF4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:35:59:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.306640, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-35-58-496372_run_instance.out.The output status is not "SAT"
18:36:00.150 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1602A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:00:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:01.503 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1602A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:01:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:01.504 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1602A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.19	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:01.504 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1602A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.19	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:01.504 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1602A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.19	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:01.504 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1602A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:01.504 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1602A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:01:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.247960, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-0-129944_run_instance.out.The output status is not "SAT"
18:36:01.795 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1ADC7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:01:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:03.098 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1ADC7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:03:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:03.098 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1ADC7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.87/1.16	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:03.098 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1ADC7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.87/1.16	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:03.098 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1ADC7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.87/1.16	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:03.098 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1ADC7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:03.149 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1ADC7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:03:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.214760, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-1-750608_run_instance.out.The output status is not "SAT"
18:36:03.360 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1D5C2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:03:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:04.763 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1D5C2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:04:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:04.763 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1D5C2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.28	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:04.763 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1D5C2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.28	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:04.763 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1D5C2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.28	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:04.764 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1D5C2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:04.814 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1D5C2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:04:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.339120, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-3-298052_run_instance.out.The output status is not "SAT"
18:36:05.035 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x21DA6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:05:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:06.439 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x21DA6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:06:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:06.439 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x21DA6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.27	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:06.439 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x21DA6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.27	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:06.439 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x21DA6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.27	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:06.439 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x21DA6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:06.489 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x21DA6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:06:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.322880, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-5-3581_run_instance.out.The output status is not "SAT"
18:36:06.750 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x24B7C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:06:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:08.053 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x24B7C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:08:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:08.053 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x24B7C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.18	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:08.053 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x24B7C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.18	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:08.053 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x24B7C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.18	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:08.053 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x24B7C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:08.053 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x24B7C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:08:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.240020, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-6-686527_run_instance.out.The output status is not "SAT"
18:36:08.329 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x27996, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:08:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:09.732 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x27996, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:09:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:09.732 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x27996, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.28	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:09.732 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x27996, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.28	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:09.732 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x27996, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.28	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:09.732 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x27996, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:09.782 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x27996, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:09:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.333680, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-8-301836_run_instance.out.The output status is not "SAT"
18:36:10.042 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x2C158, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:09:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:11.345 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x2C158, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:11:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:11.345 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x2C158, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.20	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:11.345 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x2C158, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.20	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:11.345 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x2C158, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.20	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:11.345 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x2C158, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:11.346 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x2C158, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:11:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.253110, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-9-976071_run_instance.out.The output status is not "SAT"
18:36:11.668 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x307D1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:11:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:12.972 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x307D1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:12:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:12.972 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x307D1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.02/1.22	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:12.972 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x307D1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.02/1.22	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:12.972 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x307D1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.02/1.22	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:12.972 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x307D1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:13.022 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x307D1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:12:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.278370, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-11-608857_run_instance.out.The output status is not "SAT"
18:36:13.232 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x33734, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:13:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:14.535 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x33734, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:14:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:14.535 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x33734, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.22	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:14.535 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x33734, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.22	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:14.535 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x33734, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.22	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:14.535 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x33734, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:14.536 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x33734, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:14:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.278810, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-13-166092_run_instance.out.The output status is not "SAT"
18:36:14.795 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x36621, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:14:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:16.098 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x36621, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:16:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:16.099 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x36621, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.02/1.23	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:16.099 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x36621, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.02/1.23	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:16.099 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x36621, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.02/1.23	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:16.099 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x36621, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:16.149 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x36621, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:16:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.285400, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-14-747586_run_instance.out.The output status is not "SAT"
18:36:16.357 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3AD10, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:16:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:17.660 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3AD10, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:17:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:17.661 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3AD10, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.22	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:17.661 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3AD10, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.22	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:17.661 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3AD10, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.22	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:17.661 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3AD10, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:17.711 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3AD10, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:17:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.273950, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-16-306964_run_instance.out.The output status is not "SAT"
18:36:17.960 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3E630, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:17:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:19.263 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3E630, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:19:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:19.263 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3E630, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.86/1.19	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:19.263 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3E630, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.86/1.19	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:19.263 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3E630, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.86/1.19	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:19.263 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3E630, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:19.313 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x3E630, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:19:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.246080, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-17-917762_run_instance.out.The output status is not "SAT"
18:36:19.522 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x422EC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:19:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:20.724 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x422EC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:20:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:20.725 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x422EC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.89/1.12	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:20.725 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x422EC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.89/1.12	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:20.725 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x422EC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.89/1.12	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:20.725 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x422EC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:20.775 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x422EC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:20:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.177600, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-19-475508_run_instance.out.The output status is not "SAT"
18:36:21.039 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4653A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:21:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:22.342 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4653A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:22:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:22.342 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4653A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.19	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:22.342 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4653A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.19	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:22.342 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4653A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.19	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:22.342 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4653A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:22.392 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4653A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:22:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.244080, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-20-979242_run_instance.out.The output status is not "SAT"
18:36:22.601 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x498C8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:22:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:23.904 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x498C8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:23:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:23.904 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x498C8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.90/1.19	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:23.904 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x498C8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.90/1.19	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:23.905 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x498C8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.90/1.19	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:23.905 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x498C8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:23.955 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x498C8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:23:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.247790, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-22-540129_run_instance.out.The output status is not "SAT"
18:36:24.236 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4C614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:24:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:25.539 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4C614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:25:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:25.539 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4C614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.17	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:25.539 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4C614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.17	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:25.539 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4C614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.17	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:25.539 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4C614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:25.589 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x4C614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:25:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.228550, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-24-178226_run_instance.out.The output status is not "SAT"
18:36:25.847 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x50EA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:25:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:27.150 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x50EA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:27:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:27.150 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x50EA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.18	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:27.151 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x50EA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.18	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:27.151 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x50EA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.18	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:27.151 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x50EA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:27.151 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x50EA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:27:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.242100, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-25-782146_run_instance.out.The output status is not "SAT"
18:36:27.454 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x556C3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:27:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:28.656 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x556C3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:28:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:28.656 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x556C3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.90/1.12	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:28.656 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x556C3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.90/1.12	    print("Logging test errors at " + OUTPUT_LOG_PATH)        
18:36:28.657 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x556C3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.90/1.12	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:28.657 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x556C3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:28.657 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x556C3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:28:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.176640, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-27-385957_run_instance.out.The output status is not "SAT"
18:36:28.914 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x58480, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:28:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:30.217 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x58480, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:30:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:30.217 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x58480, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.15	  File "/root/tf-hpolib/tf-hpo/src/hpolib-main.py", line 32, in main
18:36:30.217 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x58480, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.15	    print("Logging test errors at " + LOG_PATH)        
18:36:30.217 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x58480, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.15	NameError: global name 'OUTPUT_LOG_PATH' is not defined
18:36:30.217 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x58480, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:30.268 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x58480, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:30:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.203490, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-28-847406_run_instance.out.The output status is not "SAT"
18:36:30.459 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5AE60, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:30:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:31.761 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5AE60, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:31:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:31.761 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5AE60, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.21	    stream = open(self.baseFilename, self.mode)
18:36:31.761 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5AE60, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.21	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:31.761 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5AE60, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.24	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fcf5a6733b0>> ignored
18:36:31.761 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5AE60, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:31.811 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5AE60, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:31:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.269880, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-30-406932_run_instance.out.The output status is not "SAT"
18:36:32.069 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5FA5C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:32:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:33.472 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5FA5C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:33:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:33.472 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5FA5C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.28	    stream = open(self.baseFilename, self.mode)
18:36:33.472 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5FA5C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.28	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:33.472 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5FA5C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.14/1.31	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f64414c43b0>> ignored
18:36:33.472 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5FA5C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:33.522 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x5FA5C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:33:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.336540, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-32-3750_run_instance.out.The output status is not "SAT"
18:36:33.777 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x62FC9, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:33:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:35.080 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x62FC9, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:35:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:35.080 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x62FC9, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.20	    stream = open(self.baseFilename, self.mode)
18:36:35.080 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x62FC9, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.20	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:35.080 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x62FC9, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.23	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f58c065e3b0>> ignored
18:36:35.080 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x62FC9, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:35.080 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x62FC9, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:35:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.256120, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-33-705821_run_instance.out.The output status is not "SAT"
18:36:35.288 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x67038, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:35:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:36.592 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x67038, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:36:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:36.592 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x67038, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.22	    stream = open(self.baseFilename, self.mode)
18:36:36.592 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x67038, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.22	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:36.592 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x67038, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.25	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7ff659e633b0>> ignored
18:36:36.592 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x67038, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:36.642 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x67038, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:36:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.276590, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-35-232330_run_instance.out.The output status is not "SAT"
18:36:36.902 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6A55E, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:36:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:38.205 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6A55E, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:38:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:38.205 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6A55E, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.87/1.19	    stream = open(self.baseFilename, self.mode)
18:36:38.205 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6A55E, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.87/1.19	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:38.205 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6A55E, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.97/1.22	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7efc4c7803b0>> ignored
18:36:38.205 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6A55E, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:38.305 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6A55E, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:38:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.252540, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-36-871391_run_instance.out.The output status is not "SAT"
18:36:38.513 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6E614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:38:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:39.816 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6E614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:39:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:39.816 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6E614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.16	    stream = open(self.baseFilename, self.mode)
18:36:39.816 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6E614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.16	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:39.816 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6E614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.19	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f8838a7d3b0>> ignored
18:36:39.816 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6E614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:39.866 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x6E614, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:39:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.220570, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-38-458545_run_instance.out.The output status is not "SAT"
18:36:40.172 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x722A1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:40:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:41.374 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x722A1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:41:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:41.374 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x722A1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.14	    stream = open(self.baseFilename, self.mode)
18:36:41.374 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x722A1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.14	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:41.374 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x722A1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.17	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fe67ae1e3b0>> ignored
18:36:41.374 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x722A1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:41.424 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x722A1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:41:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.193160, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-40-113821_run_instance.out.The output status is not "SAT"
18:36:41.632 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x75BF0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:41:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:42.935 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x75BF0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:42:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:42.935 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x75BF0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.20	    stream = open(self.baseFilename, self.mode)
18:36:42.935 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x75BF0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.20	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:42.935 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x75BF0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.23	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f62def3b3b0>> ignored
18:36:42.935 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x75BF0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:43.035 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x75BF0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:42:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.260410, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-41-604199_run_instance.out.The output status is not "SAT"
18:36:43.277 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x79AA7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:43:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:44.580 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x79AA7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:44:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:44.580 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x79AA7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.89/1.19	    stream = open(self.baseFilename, self.mode)
18:36:44.580 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x79AA7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.89/1.19	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:44.580 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x79AA7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.98/1.22	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f6bc96343b0>> ignored
18:36:44.580 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x79AA7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:44.680 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x79AA7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:44:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.247920, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-43-215950_run_instance.out.The output status is not "SAT"
18:36:44.889 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x7D1CC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:44:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:46.292 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x7D1CC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:46:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:46.292 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x7D1CC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.99/1.28	    stream = open(self.baseFilename, self.mode)
18:36:46.292 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x7D1CC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.99/1.28	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:46.292 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x7D1CC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.10/1.31	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f533aab93b0>> ignored
18:36:46.292 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x7D1CC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:46.343 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x7D1CC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:46:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.342320, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-44-829576_run_instance.out.The output status is not "SAT"
18:36:46.517 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x809E7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:46:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:47.920 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x809E7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:47:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:47.921 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x809E7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.25	    stream = open(self.baseFilename, self.mode)
18:36:47.921 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x809E7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.25	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:47.921 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x809E7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.28	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f08651493b0>> ignored
18:36:47.921 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x809E7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:47.971 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x809E7, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:47:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.304000, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-46-479166_run_instance.out.The output status is not "SAT"
18:36:48.227 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x847A8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:48:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:49.530 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x847A8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:49:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:49.531 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x847A8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.97/1.22	    stream = open(self.baseFilename, self.mode)
18:36:49.531 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x847A8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.97/1.22	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:49.531 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x847A8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.97/1.25	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f2a7ce953b0>> ignored
18:36:49.531 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x847A8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:49.581 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x847A8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:49:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.274850, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-48-163855_run_instance.out.The output status is not "SAT"
18:36:49.877 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x891D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:49:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:51.180 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x891D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:51:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:51.180 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x891D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.24	    stream = open(self.baseFilename, self.mode)
18:36:51.180 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x891D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.24	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:51.180 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x891D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.27	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f7daa86e3b0>> ignored
18:36:51.180 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x891D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:51.230 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x891D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:51:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.299270, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-49-822303_run_instance.out.The output status is not "SAT"
18:36:51.437 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8BD84, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:51:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:52.840 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8BD84, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:52:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:52.840 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8BD84, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.02/1.29	    stream = open(self.baseFilename, self.mode)
18:36:52.840 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8BD84, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.02/1.29	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:52.840 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8BD84, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.12/1.32	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fa0e47d03b0>> ignored
18:36:52.840 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8BD84, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:52.891 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8BD84, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:52:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.345800, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-51-374143_run_instance.out.The output status is not "SAT"
18:36:53.138 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8F031, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:53:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:54.441 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8F031, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:54:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:54.441 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8F031, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.97/1.20	    stream = open(self.baseFilename, self.mode)
18:36:54.441 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8F031, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.97/1.20	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:54.442 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8F031, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.97/1.23	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f329881b3b0>> ignored
18:36:54.442 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8F031, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:54.542 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x8F031, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:54:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.256090, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-53-107038_run_instance.out.The output status is not "SAT"
18:36:54.799 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x93360, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:54:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:56.252 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x93360, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:56:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:56.252 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x93360, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.08/1.30	    stream = open(self.baseFilename, self.mode)
18:36:56.252 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x93360, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.08/1.30	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:56.252 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x93360, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.08/1.33	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f495e19b3b0>> ignored
18:36:56.252 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x93360, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:56.302 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x93360, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:56:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.357090, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-54-758627_run_instance.out.The output status is not "SAT"
18:36:56.560 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x961D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:56:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:57.862 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x961D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:57:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:57.863 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x961D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.18	    stream = open(self.baseFilename, self.mode)
18:36:57.863 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x961D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.18	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:57.863 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x961D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.21	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fd3888573b0>> ignored
18:36:57.863 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x961D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:57.913 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x961D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:36:57:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.236520, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-56-499094_run_instance.out.The output status is not "SAT"
18:36:58.119 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9A93C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:58:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:36:59.422 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9A93C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:36:59:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:36:59.422 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9A93C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.94/1.19	    stream = open(self.baseFilename, self.mode)
18:36:59.422 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9A93C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.94/1.19	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:36:59.422 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9A93C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.22	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f69db1f53b0>> ignored
18:36:59.422 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9A93C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:36:59.472 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9A93C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:59:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.250990, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-58-57166_run_instance.out.The output status is not "SAT"
18:36:59.723 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9D387, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:36:59:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:01.026 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9D387, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:01:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:01.026 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9D387, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.18	    stream = open(self.baseFilename, self.mode)
18:37:01.026 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9D387, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.18	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:01.026 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9D387, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.21	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fe306add3b0>> ignored
18:37:01.026 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9D387, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:01.076 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x9D387, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:01:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.235980, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-36-59-693610_run_instance.out.The output status is not "SAT"
18:37:01.283 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA1F18, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:01:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:02.686 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA1F18, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:02:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:02.686 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA1F18, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.25	    stream = open(self.baseFilename, self.mode)
18:37:02.686 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA1F18, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.25	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:02.686 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA1F18, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.29	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fd96062c3b0>> ignored
18:37:02.686 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA1F18, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:02.787 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA1F18, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:02:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.313030, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-1-248528_run_instance.out.The output status is not "SAT"
18:37:03.038 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA4E1D, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:03:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:04.341 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA4E1D, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:04:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:04.341 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA4E1D, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.83/1.18	    stream = open(self.baseFilename, self.mode)
18:37:04.341 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA4E1D, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.83/1.18	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:04.341 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA4E1D, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.94/1.21	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f231e4823b0>> ignored
18:37:04.341 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA4E1D, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:04.441 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA4E1D, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:04:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.235930, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-2-981721_run_instance.out.The output status is not "SAT"
18:37:04.598 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA94F4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:04:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:05.801 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA94F4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:05:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:05.801 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA94F4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.12	    stream = open(self.baseFilename, self.mode)
18:37:05.801 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA94F4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.12	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:05.801 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA94F4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.15	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fcfa16293b0>> ignored
18:37:05.801 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA94F4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:05.851 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xA94F4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:05:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.182390, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-4-551044_run_instance.out.The output status is not "SAT"
18:37:06.151 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xAD41F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:06:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:07.554 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xAD41F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:07:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:07.554 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xAD41F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.28	    stream = open(self.baseFilename, self.mode)
18:37:07.554 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xAD41F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.28	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:07.554 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xAD41F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.11/1.31	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f8e9bcbc3b0>> ignored
18:37:07.554 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xAD41F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:07.654 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xAD41F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:07:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.336570, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-6-98663_run_instance.out.The output status is not "SAT"
18:37:07.812 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB0AD0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:07:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:09.015 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB0AD0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:09:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:09.015 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB0AD0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.90/1.12	    stream = open(self.baseFilename, self.mode)
18:37:09.015 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB0AD0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.90/1.12	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:09.015 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB0AD0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.90/1.15	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f72588f03b0>> ignored
18:37:09.015 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB0AD0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:09.065 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB0AD0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:09:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.181720, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-7-770669_run_instance.out.The output status is not "SAT"
18:37:09.365 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB5151, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:09:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:10.667 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB5151, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:10:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:10.668 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB5151, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.89/1.19	    stream = open(self.baseFilename, self.mode)
18:37:10.668 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB5151, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.89/1.19	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:10.668 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB5151, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.98/1.22	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fb6112d93b0>> ignored
18:37:10.668 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB5151, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:10.718 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB5151, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:10:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.247780, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-9-309765_run_instance.out.The output status is not "SAT"
18:37:10.975 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB80AC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:10:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:12.378 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB80AC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:12:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:12.378 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB80AC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.98/1.25	    stream = open(self.baseFilename, self.mode)
18:37:12.378 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB80AC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.98/1.25	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:12.378 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB80AC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.98/1.28	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fa36ad8f3b0>> ignored
18:37:12.378 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB80AC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:12.428 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xB80AC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:12:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.305730, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-10-919559_run_instance.out.The output status is not "SAT"
18:37:12.726 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCAB6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:12:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:14.029 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCAB6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:14:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:14.029 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCAB6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.23	    stream = open(self.baseFilename, self.mode)
18:37:14.029 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCAB6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.23	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:14.029 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCAB6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.26	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f286a03d3b0>> ignored
18:37:14.029 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCAB6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:14.079 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBCAB6, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:14:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.284350, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-12-665469_run_instance.out.The output status is not "SAT"
18:37:14.335 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBF688, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:14:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:15.638 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBF688, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:15:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:15.639 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBF688, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.17	    stream = open(self.baseFilename, self.mode)
18:37:15.639 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBF688, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.17	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:15.639 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBF688, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.20	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f33703213b0>> ignored
18:37:15.639 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBF688, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:15.689 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xBF688, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:15:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.223420, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-14-268130_run_instance.out.The output status is not "SAT"
18:37:15.937 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC2CA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:15:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:17.239 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC2CA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:17:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:17.240 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC2CA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.23	    stream = open(self.baseFilename, self.mode)
18:37:17.240 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC2CA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.23	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:17.240 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC2CA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.26	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f1b404563b0>> ignored
18:37:17.240 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC2CA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:17.340 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC2CA4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:17:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.285930, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-15-879299_run_instance.out.The output status is not "SAT"
18:37:17.497 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC6C64, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:17:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:18.799 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC6C64, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:18:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:18.800 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC6C64, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.17	    stream = open(self.baseFilename, self.mode)
18:37:18.800 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC6C64, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.17	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:18.800 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC6C64, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.20	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f5ea5ed43b0>> ignored
18:37:18.800 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC6C64, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:18.900 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC6C64, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:18:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.227810, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-17-452854_run_instance.out.The output status is not "SAT"
18:37:19.151 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC94CF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:19:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:20.554 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC94CF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:20:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:20.554 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC94CF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.26	    stream = open(self.baseFilename, self.mode)
18:37:20.554 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC94CF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.26	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:20.554 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC94CF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.29	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f270a26e3b0>> ignored
18:37:20.554 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC94CF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:20.655 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xC94CF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:20:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.321530, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-19-102077_run_instance.out.The output status is not "SAT"
18:37:20.862 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xCE240, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:20:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:22.264 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xCE240, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:22:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:22.264 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xCE240, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.28	    stream = open(self.baseFilename, self.mode)
18:37:22.264 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xCE240, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.28	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:22.264 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xCE240, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.13/1.31	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f48786063b0>> ignored
18:37:22.264 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xCE240, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:22.314 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xCE240, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:22:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.335650, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-20-792885_run_instance.out.The output status is not "SAT"
18:37:22.615 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD16C5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:22:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:24.018 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD16C5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:24:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:24.018 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD16C5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.98/1.26	    stream = open(self.baseFilename, self.mode)
18:37:24.018 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD16C5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.98/1.26	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:24.018 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD16C5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.98/1.29	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f2905d203b0>> ignored
18:37:24.018 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD16C5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:24.119 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD16C5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:24:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.318430, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-22-560312_run_instance.out.The output status is not "SAT"
18:37:24.326 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD581C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:24:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:25.629 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD581C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:25:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:25.629 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD581C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.21	    stream = open(self.baseFilename, self.mode)
18:37:25.629 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD581C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.21	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:25.629 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD581C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.24	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7ff7b701c3b0>> ignored
18:37:25.629 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD581C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:25.730 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xD581C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:25:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.271550, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-24-277371_run_instance.out.The output status is not "SAT"
18:37:25.986 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDA358, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:25:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:27.389 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDA358, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:27:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:27.389 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDA358, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.95/1.26	    stream = open(self.baseFilename, self.mode)
18:37:27.389 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDA358, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.95/1.26	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:27.390 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDA358, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.95/1.29	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fb905e113b0>> ignored
18:37:27.390 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDA358, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:27.440 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDA358, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:27:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.314650, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-25-913295_run_instance.out.The output status is not "SAT"
18:37:27.696 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDCDF8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:27:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:28.999 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDCDF8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:28:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:28.999 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDCDF8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.19	    stream = open(self.baseFilename, self.mode)
18:37:28.999 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDCDF8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.92/1.19	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:28.999 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDCDF8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.22	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fac797223b0>> ignored
18:37:28.999 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDCDF8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:29.100 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDCDF8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:29:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.245990, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-27-645487_run_instance.out.The output status is not "SAT"
18:37:29.401 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDFAC3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:29:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:30.703 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDFAC3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:30:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:30.704 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDFAC3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.21	    stream = open(self.baseFilename, self.mode)
18:37:30.704 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDFAC3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.21	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:30.704 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDFAC3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.24	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f0f27e393b0>> ignored
18:37:30.704 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDFAC3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:30.804 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xDFAC3, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:30:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.272030, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-29-352135_run_instance.out.The output status is not "SAT"
18:37:31.011 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE43D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:31:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:32.364 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE43D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:32:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:32.364 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE43D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.21	    stream = open(self.baseFilename, self.mode)
18:37:32.364 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE43D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.21	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:32.364 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE43D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.24	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fca2927b3b0>> ignored
18:37:32.364 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE43D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:32.414 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE43D4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:32:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.267910, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-30-968038_run_instance.out.The output status is not "SAT"
18:37:32.708 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE77FF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:32:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:34.011 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE77FF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:34:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:34.011 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE77FF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.19	    stream = open(self.baseFilename, self.mode)
18:37:34.011 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE77FF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.19	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:34.011 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE77FF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.22	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f00828783b0>> ignored
18:37:34.011 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE77FF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:34.111 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xE77FF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:34:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.251450, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-32-658957_run_instance.out.The output status is not "SAT"
18:37:34.318 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEB9B0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:34:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:35.721 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEB9B0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:35:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:35.721 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEB9B0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.11/1.33	    stream = open(self.baseFilename, self.mode)
18:37:35.721 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEB9B0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.11/1.33	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:35.721 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEB9B0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.11/1.36	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f75e7b1e3b0>> ignored
18:37:35.721 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEB9B0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:35.821 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEB9B0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:35:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.391570, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-34-273295_run_instance.out.The output status is not "SAT"
18:37:36.069 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEE1F2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:36:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:37.372 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEE1F2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:37:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:37.372 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEE1F2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.24	    stream = open(self.baseFilename, self.mode)
18:37:37.372 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEE1F2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.24	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:37.372 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEE1F2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.00/1.27	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f866a3af3b0>> ignored
18:37:37.372 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEE1F2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:37.472 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xEE1F2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:37:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.294480, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-36-18690_run_instance.out.The output status is not "SAT"
18:37:37.678 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF2F8C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:37:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:38.981 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF2F8C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:38:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:38.981 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF2F8C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.91/1.19	    stream = open(self.baseFilename, self.mode)
18:37:38.981 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF2F8C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.91/1.19	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:38.981 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF2F8C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.01/1.22	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f3c231573b0>> ignored
18:37:38.981 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF2F8C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:39.082 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF2F8C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:39:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.249080, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-37-620126_run_instance.out.The output status is not "SAT"
18:37:39.281 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF7CDC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:39:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:40.685 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF7CDC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:40:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:40.685 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF7CDC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.10/1.30	    stream = open(self.baseFilename, self.mode)
18:37:40.685 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF7CDC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.10/1.30	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:40.685 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF7CDC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.10/1.33	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f0d2f3a73b0>> ignored
18:37:40.685 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF7CDC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:40.785 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xF7CDC, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:40:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.353870, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-39-230936_run_instance.out.The output status is not "SAT"
18:37:41.042 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFA568, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:41:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:42.395 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFA568, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:42:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:42.395 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFA568, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.20	    stream = open(self.baseFilename, self.mode)
18:37:42.395 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFA568, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.93/1.20	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:42.395 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFA568, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.23	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7fa37f7cb3b0>> ignored
18:37:42.395 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFA568, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:42.445 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFA568, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:42:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.253260, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-40-996514_run_instance.out.The output status is not "SAT"
18:37:42.696 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFD5D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:42:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:44.149 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFD5D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:44:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:44.149 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFD5D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.27	    stream = open(self.baseFilename, self.mode)
18:37:44.149 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFD5D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.03/1.27	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:44.149 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFD5D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.14/1.30	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f05e65a23b0>> ignored
18:37:44.149 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFD5D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:44.199 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0xFD5D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:37:44:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.324220, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-42-650408_run_instance.out.The output status is not "SAT"
18:37:44.406 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x101B44, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:44:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:45.809 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x101B44, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:45:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:45.809 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x101B44, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.24	    stream = open(self.baseFilename, self.mode)
18:37:45.809 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x101B44, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.24	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:45.809 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x101B44, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  2.04/1.27	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f35a71a13b0>> ignored
18:37:45.809 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x101B44, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:45.909 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x101B44, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:45:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.301990, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-44-352465_run_instance.out.The output status is not "SAT"
18:37:46.184 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x106853, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:46:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:47.487 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x106853, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [CRITICAL] [18:37:47:HPOlib.runsolver_wrapper] We could not find anything matching our regexp. Setting the target algorithm runtime to the time measured by the runsolver. Last lines of your output:
18:37:47.487 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x106853, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.89/1.18	    stream = open(self.baseFilename, self.mode)
18:37:47.487 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x106853, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.89/1.18	IOError: [Errno 2] No such file or directory: '/root/tf-hpolib/tf-hpo/benchmark/log/hpolib.csv'
18:37:47.487 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x106853, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  1.99/1.21	Exception AttributeError: "PerformanceCSVLogger instance has no attribute 'logger'" in <bound method PerformanceCSVLogger.__del__ of <modules.logger.PerformanceCSVLogger instance at 0x7f66829003b0>> ignored
18:37:47.487 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x106853, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  
18:37:47.588 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x106853, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:47:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 1.239980, 1, 1000.000000, -1, Please have a look at /root/tf-hpolib/tf-hpo/benchmark/smac_2_06_01-dev_23_2016-10-25--18-35-28-82753/2016-10-25--18-37-46-134301_run_instance.out.The output status is not "SAT"
18:37:47.846 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x109120, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:47:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:37:59.736 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x109120, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:37:59:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 11.728700, 1, 89.720000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:38:00.186 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x10DBFF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:38:00:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:38:16.263 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x10DBFF, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:38:16:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 15.921800, 1, 5.600000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:38:16.472 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x11070D, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:38:16:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:38:55.894 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x11070D, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:38:55:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 39.205000, 1, 56.650000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:38:56.230 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x113335, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:38:56:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:39:06.557 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x113335, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:39:06:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 10.154900, 1, 3.570000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:39:06.866 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x117D8D, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:39:06:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:39:26.009 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x117D8D, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:39:26:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 19.080200, 1, 11.930000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:39:26.298 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x11F39B, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:39:26:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:39:36.031 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x11F39B, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:39:36:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 9.570250, 1, 2.240000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:39:36.309 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1241D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:39:36:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:39:46.633 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1241D5, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:39:46:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 10.101500, 1, 1.980000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:39:46.892 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x126A0D, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:39:46:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:40:13.491 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x126A0D, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:40:13:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 26.427100, 1, 3.620000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:40:13.769 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x12E05F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:40:13:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:40:37.214 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x12E05F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:40:37:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 23.262700, 1, 89.720000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:40:37.592 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x12E0A1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:40:37:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:40:53.774 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x12E0A1, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:40:53:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 16.073400, 1, 45.080000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:40:54.032 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x135734, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:40:53:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:42:19.532 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x135734, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:42:19:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 85.327600, 1, 89.720000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:42:19.842 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x13A32F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:42:19:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:43:26.359 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x13A32F, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:43:26:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 66.384500, 1, 89.720000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:43:26.667 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x13CDB4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:43:26:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:43:35.946 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x13CDB4, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:43:35:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 9.192720, 1, 3.620000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:43:36.321 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1407AE, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:43:36:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:43:42.997 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1407AE, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:43:42:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 6.595530, 1, 9.320000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:43:43.253 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x144406, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:43:43:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:44:13.970 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x144406, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:44:13:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 30.547600, 1, 4.900000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:44:14.298 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x148B27, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:44:14:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:45:04.380 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x148B27, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:45:04:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 49.963900, 1, 89.720000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:45:04.637 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x14BA8A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:45:04:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:45:19.418 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x14BA8A, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:45:19:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 14.670700, 1, 89.720000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:45:19.694 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1506E0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:45:19:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:45:29.225 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1506E0, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:45:29:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 9.349550, 1, 1.730000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:45:29.487 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x15313E, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:45:29:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:48:25.583 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x15313E, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:48:25:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 175.951000, 1, 89.720000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:48:25.898 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x156D42, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:48:25:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:48:51.003 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x156D42, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:48:50:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 24.954000, 1, 2.760000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:48:51.311 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x15A7C2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:48:51:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:49:01.386 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x15A7C2, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:49:01:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 9.981870, 1, 4.350000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:49:01.722 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x15F6AA, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:49:01:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:49:22.871 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x15F6AA, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:49:22:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 20.972200, 1, 2.630000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:49:23.129 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x161E35, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:49:23:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:51:16.323 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x161E35, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:51:16:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 113.060000, 1, 90.200000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:51:16.695 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x165F4B, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:51:16:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:51:22.622 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x165F4B, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:51:22:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 5.729540, 1, 13.430000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:51:22.930 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1694F8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:51:22:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:51:49.637 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x1694F8, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:51:49:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 26.526700, 1, 3.790000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:51:49.965 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x16DE51, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:51:49:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:52:17.421 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x16DE51, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:52:17:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 27.345200, 1, 2.410000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:52:17.680 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x170BCA, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:52:17:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:53:58.600 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x170BCA, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:53:58:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 100.757000, 1, 89.720000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:53:58.930 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x174703, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:53:58:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
18:54:13.470 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x174703, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR] [INFO] [18:54:13:HPOlib.runsolver_wrapper] Result for ParamILS: SAT, 14.341300, 1, 2.460000, -1, python /root/tf-hpolib/tf-hpo/src/hpolib-main.py
18:54:13.677 [Command Line Target Algorithm Evaluator Thread (Standard Error Processor)<Instance:1, Seed:-1, Config:0x17825C, Kappa:2.147483647E9>] WARN  c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - [PROCESS-ERR]  [INFO] [18:54:13:HPOlib.runsolver_wrapper] -----------------------RUNNING RUNSOLVER----------------------------
