0.94/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
0.94/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
0.94/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
0.94/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
0.94/0.11	I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
1.43/0.64	tensorflow CNN code started
1.43/0.64	Params: {'filter_size': '8.0', 'fc_depth': '485.0', 'conv1_depth': '392.0'}
1.63/19.81	('Successfully downloaded', 'train-images-idx3-ubyte.gz', 9912422, 'bytes.')
1.63/20.69	('Successfully downloaded', 'train-labels-idx1-ubyte.gz', 28881, 'bytes.')
1.65/25.32	('Successfully downloaded', 't10k-images-idx3-ubyte.gz', 1648877, 'bytes.')
1.65/26.00	('Successfully downloaded', 't10k-labels-idx1-ubyte.gz', 4542, 'bytes.')
2.05/26.46	Traceback (most recent call last):
2.05/26.46	  File "../convolutional-hpolib.py", line 385, in <module>
2.05/26.46	    result = main(params, **args)
2.05/26.46	  File "../convolutional-hpolib.py", line 376, in main
2.05/26.46	    y = train_mnist(dataset, flags)
2.05/26.46	  File "../convolutional-hpolib.py", line 231, in train_mnist
2.05/26.46	    vars = init_vars(int(flags["filter_size"]), int(flags["conv1_depth"]), int(flags["conv2_depth"]), int(flags["fc_depth"]))
2.05/26.46	ValueError: invalid literal for int() with base 10: '8.0'
